<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.18362.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <!-- Assembly Metadata -->
    <AssemblyName>MITMPulse</AssemblyName>
    <RootNamespace>MITMPulse</RootNamespace>
    <Authors>Francesco Dipietromaria</Authors>
    <Company>dpmworld.net</Company>
    <Copyright>Copyright © 2026 Francesco Dipietromaria (www.dpmworld.net)</Copyright>
    <Version>1.0.13</Version>
    <AssemblyVersion>1.0.13.0</AssemblyVersion>
    <FileVersion>1.0.13.0</FileVersion>

    <!-- App Branding -->
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>

    <!-- Deployment Configuration & Compression -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      <CustomToolNamespace>MITMPulse.Resources</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
